export const Categories = [
            'Alexa Skills',
            'Amazon Devices',
            'Appliances',
            'Apps & Games',
            'Audible Audiobooks',
            'Baby',
            'Books',
            'Car & Motorbike',
            'Clothing & Accessories',
            'Collectibles',
            'Computers & Accessories',
            'Deals',
            'Electronics',
            'Furniture',
            'Garden & Outdoors',
            'Gift Cards',
            'Grocery & Gourmet Foods',
            'Health & Personal Care',
            'Industrial & Scientific',
            'Jewellery',
            'Kindle Store',
            'Luggage & Bags',
            'Luxury Beauty',
            'Movies & TV Shows',
            'MP3 Music',
            'Music',
            'Musical Instruments',
            'Office Products',
            'Pet Supplies',
            'Prime Video',
            'Shoes & Handbags',
]